name: learning_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^4.0.2+2
  dio: ^3.0.10
  provider: ^4.3.2+3
  connectivity: ^2.0.2
  image_picker: ^0.6.7+21
  file_picker: ^2.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true